baseURL = "https://yashmehrotra.com/"
languageCode = "en-us"
title = "Yash Mehrotra"
theme = "hugo-coder"
# disqusShortname = "username" # delete this to disable disqus comments
publishDir = "../"

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Yash Mehrotra"
    description = "Developer · Explorer · Hacker · Open-Source"
    info = "Developer · Explorer · Hacker · Open-Source"
    githubUsername = "yashmehrotra"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"
    colorscheme = "light"

#    footercontent = "Enter a text here."

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true

[params.fathomAnalytics]
    siteID = "SKSNA"
    serverURL = "analytics.yashmehrotra.com"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/pdf/yash_mehrotra_resume.pdf"
    name = "Resume"
    weight = 4

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 1
    url = "https://twitter.com/yashm95"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/yashmehrotra"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://in.linkedin.com/in/yashmehrotra"
